context:
  name: certbot-dns-ovh
  version: "5.8.0"

package:
  name: certbot-dns-ovh
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/certbot-dns-ovh/certbot_dns_ovh-${{ version }}.tar.gz
  sha256: da6e4e6e845e676abb23529f165a0237a0a8bb4b19913dfc6a4d36876624f810

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - acme >=${{ version }}
    - certbot >=${{ version }}
    - dns-lexicon >=3.15.1

tests:
  - python:
      imports:
        - certbot_dns_ovh
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://certbot.eff.org
  summary: OVH DNS Authenticator plugin for Certbot
  license: Apache-2.0
  license_file: LICENSE.txt
  documentation: https://certbot.eff.org
  repository: https://github.com/certbot/certbot

extra:
  recipe-maintainers:
    - pavelzw
