context:
  name: certbot-dns-ovh
  version: "5.3.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: f4b30ea9e94d663431a9522914892bd8694f44cfed8c50a8545b2677b976b47d

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - acme >=${{ version }}
    - certbot >=${{ version }}
    - dns-lexicon >=3.15.1

tests:
  - python:
      imports:
        - certbot_dns_ovh
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://certbot.eff.org
  summary: OVH DNS Authenticator plugin for Certbot
  license: Apache-2.0
  license_file: LICENSE.txt
  documentation: https://certbot.eff.org
  repository: https://github.com/certbot/certbot

extra:
  recipe-maintainers:
    - pavelzw
